#Chapter 4 
##NumPy
Rachel, geçen sefer çalışan verilerini temizleme ve yapılandırma şeklinizden çok memnun ama işleri bir adım daha ileri taşımak istiyor. Satış ekibi, çalışanların performansını yalnızca elde ettikleri gelire göre değil, aynı zamanda çağrı sayısını ve ortalama anlaşma boyutunu da dikkate alarak takip etmek istiyor. Bunun için Rachel senden raporlamaya yönelik bir yazılım oluşturmanı istiyor. Veriler üzerinde hesaplamalar yapabilmek için Numpy kullanarak bir veri yapısı oluşturmanın en iyisi olacağına karar veriyorsunuz.

### Veriyi alın

İlk önce verileri almanız gerekiyor. Geçen bölümde ilgili bilgileri içeren listeler oluşturdunuz.

📌 3. bölümde oluşturduğunuz "isimler", "arama_numarası", "ortalama_anlaşma_boyutu" ve "gelir" listelerini kopyalayıp yapıştırın ve bunları değişkenlere atayın. 

In [67]:
#Copy the lists "names", "call_numbers", "average_deal_size", and "revenues" from chapter 3
names = ['Ben', 'Omer', 'Karen', 'Celine', 'Sue', 'Bora', 'Rose', 'Ellen', 'Bob', 'Taylor,', 'Jude']
call_numbers = [300, 10, 500, 70, 100, 100, 600, 800, 200, 450, 80]
averadge_deal_sizes=[8, 6, 24, 32, 5, 25, 25, 40, 15, 10, 12]
revenues = [2400, 60, 12000, 2275, 500, 770, 4000, 6000, 800, 1200, 500]

### NumPy'yi içe aktarma

NumPy'yi kullanarak bir veri yapısı oluşturmayı planlıyorsunuz.

📌 NumPy kütüphanesini şu şekilde içe aktarın:

In [68]:
#Import the NumPy library
import numpy as np

###İlk (temel) diziler oluşturma

Daha sonra değerleri saklayacağınız bir dizi hazırlamanız gerekiyor. İlk dizi boş olacaktır. Sayısal veri tutacağından veri tipinin tamsayı olması gerekmektedir.

📌 .array() kullanarak boş bir dizi oluşturun.

📌Veri tipini belirtmek için *dtype* parametresini kullanın.

In [69]:
#Create an empty array with the data type integer
data = np.array([],dtype = int)

###Veri ekleme işlevleri

Artık boş diziniz hazır olduğuna göre listelerdeki verileri diziye aktarmanız gerekiyor. Bunun için 2 fonksiyon fonksiyonu yaratırsınız.

1.append_names işlevi: "isimler" listesini alan ve her ismin indeksini "veri" dizisine ekleyen bir işlev.

   📌 Dizinler için for döngüsünü ve .append() yöntemini kullanın.

2. apend_performans_measures fonksiyonu: Geri kalan listelerden birini alarak çağrı sayısı, ortalama anlaşma büyüklüğü ve gelir gibi satış performansı verilerini "data" dizisine ekleyen fonksiyon.

In [70]:
#Define the append_names function
def append_names(names_list):
    global data
    for i in names_list:
        data = np.append(data,names.index(i))

In [71]:
#Define the append_performance_measures function
def append_performance_mesasures(feature_list):
    global data
    data = np.append(data, feature_list)

Verileri diziye eklemek için işlevleri çağırın ve sonucu görmek için diziyi ve şeklini yazdırın.

📌 .shape() yöntemini kullanın.

In [72]:
#Use the append_names and append_sales_performance_measures to add the data
append_names(names)
append_performance_mesasures(call_numbers)
append_performance_mesasures(averadge_deal_sizes)
append_performance_mesasures(revenues)


#Print the array and its shape to see the result
print(data)
print(data.shape)

[    0     1     2     3     4     5     6     7     8     9    10   300
    10   500    70   100   100   600   800   200   450    80     8     6
    24    32     5    25    25    40    15    10    12  2400    60 12000
  2275   500   770  4000  6000   800  1200   500]
(44,)


###Diziyi yeniden şekillendirin

Ancak bu şekilde diziniz pek yapılandırılmış değil. Onunla daha iyi çalışabilmek için 2 boyutlu bir diziye ihtiyacınız var. Orijinal veriler, her biri 11 değere sahip 4 listeden oluşuyordu. Yani "data" dizisinin 4 satırı ve 11 sütunu olması gerekir. Daha sonra sonucu yazdırın.

📌 Dizideki değerleri yeniden düzenlemek için .reshape() yöntemini kullanın.


In [73]:
#Use the .reshape() method to change the array structure to 4 rows and 11 columns
data = data.reshape(4,11)

#Print the resulting array and its shape
print(data)
print(data.shape)

[[    0     1     2     3     4     5     6     7     8     9    10]
 [  300    10   500    70   100   100   600   800   200   450    80]
 [    8     6    24    32     5    25    25    40    15    10    12]
 [ 2400    60 12000  2275   500   770  4000  6000   800  1200   500]]
(4, 11)


###Değerlere erişme

Dizinin içinde değerlere farklı yollardan erişebilirsiniz.

1. Her satırı ayrı ayrı yazdırın.

   📌Erişmek istediğiniz satırın dizi adını ve indeksini yazın.


In [74]:
#Print the name indexes
print(data[0])

[ 0  1  2  3  4  5  6  7  8  9 10]


In [75]:
#Print the number of calls
print(data[1])

[300  10 500  70 100 100 600 800 200 450  80]


In [76]:
#Print the average deal sizes
print(data[2])

[ 8  6 24 32  5 25 25 40 15 10 12]


In [77]:
#Print the revenues 
print(data[3])

[ 2400    60 12000  2275   500   770  4000  6000   800  1200   500]


2. Belirli bir değeri yazdırın.

   📌 Erişmek istediğiniz değerin satırının ve sütununun indeksini verin.
   Örneğin Ellen'ın elde ettiği geliri elde etmek için 3. satır ve 7. sütundaki değeri belirtin.

In [78]:
#Print the revenue generated by Ellen
print(data[3,7])

6000


###Verileri analiz etme

Harika, diziniz hazır!

Satış ekibinin bir çalışanın performans puanını hesaplamak için kullandıkları bir formül vardır.


\begin{align}
        \text{Performance} = \frac{\text{Average deal size x Revenue}}{\text{Number of calls}}
    \end{align}

📌Bu formülü uygulamak için “hesaplama_performansı” adında bir fonksiyon oluşturun. Giriş olarak çalışanın adını almalıdır.

In [79]:
#Define the function calculate_performance
def calculate_performance(employee_name):
    idx = names.index(employee_name)
    number_of_calls = data[1,idx]
    avg_deal_size = data[2,idx]
    revenue = data[3,idx]
    
    score = ((avg_deal_size * revenue)/number_of_calls)
    return score

###Denemek

Ellen'ın performans puanını kontrol edip sonucu yazdıralım.

In [80]:
#Use the calculate performance function to print Ellen's performance
print(calculate_performance("Ellen"))

300.0


###Her çalışanın performansını hesaplayın
Artık her çalışanın performans puanını hesaplayıp bu puanları bir listeye eklemeniz gerekiyor.

📌 Puanları tutmak için boş bir "performans_skorları" listesi oluşturun.

📌 Puanları tamsayı tipi verilere dönüştürmek ve bunu "s Performance_scores" listesine eklemek için bir for döngüsü kullanın.

In [81]:
#Calculate the performance of each employee
performance_scores = []
for name in names:
    score = int(calculate_performance(name))
    performance_scores.append(score)

###Puanları "veri" dizisine ekleyin

Daha sonra, puanları "veri" dizinize eklemeniz ve sonucu yazdırmanız gerekir.

📌 "performans_scores" listesini "data" dizisine eklemek için .concatenate() yöntemini kullanın.

In [82]:
#Add the "performance_scores" list to the "data" array
data = np.concatenate((data,[performance_scores]), axis = 0)

#Print the resulting array
print(data)

[[    0     1     2     3     4     5     6     7     8     9    10]
 [  300    10   500    70   100   100   600   800   200   450    80]
 [    8     6    24    32     5    25    25    40    15    10    12]
 [ 2400    60 12000  2275   500   770  4000  6000   800  1200   500]
 [   64    36   576  1040    25   192   166   300    60    26    75]]


###En iyi ve en kötü performans gösteren çalışanları bulun

Son olarak, en iyi ve en kötü performans gösteren çalışanları belirlemeniz gerekir.

📌 En iyi ve en kötü performans gösteren çalışanların endeksini bulmak için .argmax() ve .argmin() yöntemlerini kullanın.

In [83]:
#Use .argmax() and .argmin() methods to determine the best and worst performing employees
idx_best_employee = np.argmax(data[4])
idx_worst_employee = np.argmin((data[4]))
#Print out the results
print(f"Best Performance Employee: {names[idx_best_employee]}")
print(f"Woerst Performance Employee: {names[idx_worst_employee]}")

Best Performance Employee: Celine
Woerst Performance Employee: Sue
